# Generated by Django 3.2 on 2021-04-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('SC', 'Scheduled'), ('R', 'Running'), ('C', 'Completed'), ('I', 'Idle'), ('M', 'Multi-Run')], max_length=2),
        ),
    ]
