# Generated by Django 3.2 on 2021-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210413_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(blank=True, choices=[('SC', 'Scheduled'), ('R', 'Running'), ('C', 'Completed'), ('I', 'Idle'), ('M', 'Multi-Run')], max_length=2),
        ),
    ]
